### ISSUE TITLE
Add gpt4all support / Add autogpt4all script packaging? 

### ISSUE THREAD

**Issue by zudsniper** [kurtosis-tech/autogpt-package#82]
[`nomic-ai/gpt4all`](https://github.com/nomic-ai/gpt4all) has quickly been rising in popularity as an alternative to OpenAI's GPT models that can be run entirely locally, using various generative pre-trained transformer model types, as described in detail in the aforementioned repository's `README.md`. 

fortunately, another github user already created [`aorumbayev/autogpt4all`](https://github.com/aorumbayev/autogpt4all), which is a bash script allowing the use of `gpt4all` models with `autogpt` through a [`go-skynet/LocalAI`](https://github.com/go-skynet/LocalAI) server, as described on the repository. Perhaps you guys at the Kurtosis would consider building a `*-package` repository for this script as well.

I wanted to mention this as I really like Kurtosis, but currently I can't accomplish what I mean to do with it, as I do not have a GPT4 API key.  

hopefully you consider this! 
be well

**Comment by h4ck3rk3y** [comment]
I have added support for what you asked for you  can try it using

```
kurtosis run github.com/kurtosis-tech/autogpt-package  '{"GPT_4ALL": true}'
```

For different model https://github.com/kurtosis-tech/autogpt-package/tree/main#run-without-openai

**Comment by zudsniper** [comment]
> I have added support for what you asked for you can try it using
> 
> ```
> kurtosis run github.com/kurtosis-tech/autogpt-package  '{"GPT_4ALL": true}'
> ```
> 
> For different model https://github.com/kurtosis-tech/autogpt-package/tree/main#run-without-openai

Wow, thank you! I'm super impressed with you kurtosis in terms of staying on top of all this stuff.

Be well
